### Generated by rprotoc. DO NOT EDIT!
### <proto file: message_protocol.proto>
# package Messages;
# 
# message Helo {
#     required uint32 userId = 1;
#     required int32 chunkSize = 2;
# }
# 
# message Put {
#     required bytes idTransaction = 1;
#     required uint32 msgSize = 2;
#     required bytes checkSum = 3;
# }
# 
# message Ack {
#     required uint32 chunkNumber = 1;
#     required EndType type = 2 [default = ACK];
# }
# 
# message Data {
#     required uint32 chunkNumber = 1;
#     required bytes data = 2;
# }
# 
# enum EndType {
#     ACK = 1;
#     ACK_END = 2;
#     DROP_END = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Messages
  class Helo < ::Protobuf::Message
    defined_in __FILE__
    required :uint32, :userId, 1
    required :int32, :chunkSize, 2
  end
  class Put < ::Protobuf::Message
    defined_in __FILE__
    required :bytes, :idTransaction, 1
    required :uint32, :msgSize, 2
    required :bytes, :checkSum, 3
  end
  class Ack < ::Protobuf::Message
    defined_in __FILE__
    required :uint32, :chunkNumber, 1
    required :EndType, :type, 2, :default => :ACK
  end
  class Data < ::Protobuf::Message
    defined_in __FILE__
    required :uint32, :chunkNumber, 1
    required :bytes, :data, 2
  end
  class EndType < ::Protobuf::Enum
    defined_in __FILE__
    ACK = value(:ACK, 1)
    ACK_END = value(:ACK_END, 2)
    DROP_END = value(:DROP_END, 3)
  end
end
